/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cap_presentacion;

import cap_datos.ListaEntradas;
import cap_datos.ListaSalidas;
import cap_logica.Entrada;
import cap_logica.Salida;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sh
 */
public class IngresoMetodos extends javax.swing.JPanel {
    
    private static DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();

    /**
     * Creates new form Metodoss
     */
    public IngresoMetodos() {
        initComponents();
        
        modeloCombo.removeAllElements();
        modeloCombo.addElement("- Seleccionar -");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        etqCantidad = new javax.swing.JLabel();
        etqPrecio = new javax.swing.JLabel();
        etqDetalle = new javax.swing.JLabel();
        cajaCantidad = new javax.swing.JTextField();
        cajaPrecio = new javax.swing.JTextField();
        cajaDetalle = new javax.swing.JTextField();
        botonEntrada = new javax.swing.JButton();
        botonSalida = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        comboRegistros = new javax.swing.JComboBox<>();
        botonEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        etqCantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqCantidad.setText("> Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 0, 0);
        add(etqCantidad, gridBagConstraints);

        etqPrecio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqPrecio.setText("> Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 0, 0);
        add(etqPrecio, gridBagConstraints);

        etqDetalle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqDetalle.setText("> Detalle:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 0, 0);
        add(etqDetalle, gridBagConstraints);

        cajaCantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaCantidad.setForeground(new java.awt.Color(153, 153, 153));
        cajaCantidad.setText("Numero de objetos");
        cajaCantidad.setCaretPosition(0);
        cajaCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaCantidadMousePressed(evt);
            }
        });
        cajaCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaCantidadKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 50);
        add(cajaCantidad, gridBagConstraints);

        cajaPrecio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaPrecio.setForeground(new java.awt.Color(153, 153, 153));
        cajaPrecio.setText("Precio unitario");
        cajaPrecio.setCaretPosition(0);
        cajaPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaPrecioMousePressed(evt);
            }
        });
        cajaPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaPrecioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaPrecioKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 190;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 50);
        add(cajaPrecio, gridBagConstraints);

        cajaDetalle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaDetalle.setForeground(new java.awt.Color(153, 153, 153));
        cajaDetalle.setText("Detalle");
        cajaDetalle.setCaretPosition(0);
        cajaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaDetalleMousePressed(evt);
            }
        });
        cajaDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaDetalleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaDetalleKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 50);
        add(cajaDetalle, gridBagConstraints);

        botonEntrada.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        botonEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap_imagenes/entradaDatos x48.png"))); // NOI18N
        botonEntrada.setText("Entrada");
        botonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntradaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(70, 0, 50, 0);
        add(botonEntrada, gridBagConstraints);

        botonSalida.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        botonSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap_imagenes/salidaDatos x48.png"))); // NOI18N
        botonSalida.setText("Salida");
        botonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalidaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(70, 0, 50, 0);
        add(botonSalida, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 80);
        add(jSeparator1, gridBagConstraints);

        comboRegistros.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        comboRegistros.setModel(modeloCombo);
        comboRegistros.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboRegistrosPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(56, 70, 0, 50);
        add(comboRegistros, gridBagConstraints);

        botonEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap_imagenes/basurero x32.png"))); // NOI18N
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 0, 0);
        add(botonEliminar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntradaActionPerformed
        
        
        try{
            Entrada e = new Entrada();
            
            e.setDetalle(cajaDetalle.getText());
            e.setCantidad(Integer.parseInt(cajaCantidad.getText()));
            e.setPrecio(Float.parseFloat(cajaPrecio.getText()));            
            
            ListaEntradas.agregar(e);
            modeloCombo.addElement(e);
            
            cajaDetalle.setText("Detalle");
            cajaDetalle.setForeground(new Color(153,153,153));
            cajaDetalle.setCaretPosition(0);
            cajaCantidad.setText("Numero de objetos");
            cajaCantidad.setForeground(new Color(153,153,153));
            cajaCantidad.setCaretPosition(0);
            cajaPrecio.setText("Precio unitario");
            cajaPrecio.setForeground(new Color(153,153,153));
            cajaPrecio.setCaretPosition(0);
            
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEntradaActionPerformed

    private void comboRegistrosPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboRegistrosPopupMenuWillBecomeInvisible
        if(comboRegistros.getSelectedIndex() == 0){
            botonEliminar.setEnabled(false);
        }else{
            botonEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_comboRegistrosPopupMenuWillBecomeInvisible

    private void cajaCantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaCantidadMousePressed

        if(cajaCantidad.getText().equals("Numero de objetos")){

            cajaCantidad.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaCantidadMousePressed

    private void cajaCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCantidadKeyPressed

        if(cajaCantidad.getText().equals("Numero de objetos")){

            cajaCantidad.setForeground(new Color(0,0,0));
            cajaCantidad.setText("");
        }
    }//GEN-LAST:event_cajaCantidadKeyPressed

    private void cajaCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCantidadKeyReleased
        boolean letra = false;
        
        if(cajaCantidad.getCaretPosition() == 0 && cajaCantidad.getText().equals("")){

            cajaCantidad.setText("Numero de objetos");
            cajaCantidad.setForeground(new Color(153,153,153));
            cajaCantidad.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaCantidad.getText().length(); i++) {
                char c = cajaCantidad.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }
            
            if(letra == true){
                cajaCantidad.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaCantidad.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaCantidadKeyReleased

    private void cajaPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaPrecioMousePressed
        if(cajaPrecio.getText().equals("Precio unitario")){

            cajaPrecio.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaPrecioMousePressed

    private void cajaPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaPrecioKeyPressed
        if(cajaPrecio.getText().equals("Precio unitario")){

            cajaPrecio.setForeground(new Color(0,0,0));
            cajaPrecio.setText("");
        }
    }//GEN-LAST:event_cajaPrecioKeyPressed

    private void cajaPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaPrecioKeyReleased
        boolean letra = false;
        
        if(cajaPrecio.getCaretPosition() == 0 && cajaPrecio.getText().equals("")){

            cajaPrecio.setText("Precio unitario");
            cajaPrecio.setForeground(new Color(153,153,153));
            cajaPrecio.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaPrecio.getText().length(); i++) {
                char c = cajaPrecio.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }
            
            if(letra == true){
                cajaPrecio.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaPrecio.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaPrecioKeyReleased

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        try{
            boolean banEntrada = false;

            for (int i = 0; i < ListaEntradas.getDatos().size(); i++) {
                Entrada e = ListaEntradas.getDatos().get(i);

                if(e.toString().equals(comboRegistros.getSelectedItem().toString())){
                    banEntrada = true;
                }
            }

            if(banEntrada == true){
                ListaEntradas.eliminar((Entrada)comboRegistros.getSelectedItem());
            }else{
                ListaSalidas.eliminar((Salida)comboRegistros.getSelectedItem());
            }

            modeloCombo.removeElementAt(comboRegistros.getSelectedIndex());
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalidaActionPerformed
        try{  
            Salida s = new Salida();
            
            s.setDetalle(cajaDetalle.getText());
            s.setCantidad(Integer.parseInt(cajaCantidad.getText()));
            s.setPrecio(Float.parseFloat(cajaPrecio.getText()));
            
            ListaSalidas.agregar(s);
            modeloCombo.addElement(s);
            
            cajaDetalle.setText("Detalle");
            cajaDetalle.setForeground(new Color(153,153,153));
            cajaDetalle.setCaretPosition(0);
            cajaCantidad.setText("Numero de objetos");
            cajaCantidad.setForeground(new Color(153,153,153));
            cajaCantidad.setCaretPosition(0);
            cajaPrecio.setText("Precio unitario");
            cajaPrecio.setForeground(new Color(153,153,153));
            cajaPrecio.setCaretPosition(0);
            
        }catch(Exception  error){ 
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonSalidaActionPerformed

    private void cajaDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaDetalleMousePressed
        if(cajaDetalle.getText().equals("Detalle")){

            cajaDetalle.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaDetalleMousePressed

    private void cajaDetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDetalleKeyReleased

        if(cajaDetalle.getCaretPosition() == 0 && cajaDetalle.getText().equals("")){

            cajaDetalle.setText("Detalle");
            cajaDetalle.setForeground(new Color(153,153,153));
            cajaDetalle.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaDetalleKeyReleased

    private void cajaDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDetalleKeyPressed
        if(cajaDetalle.getText().equals("Detalle")){

            cajaDetalle.setForeground(new Color(0,0,0));
            cajaDetalle.setText("");
        }
    }//GEN-LAST:event_cajaDetalleKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEntrada;
    private javax.swing.JButton botonSalida;
    private javax.swing.JTextField cajaCantidad;
    private javax.swing.JTextField cajaDetalle;
    private javax.swing.JTextField cajaPrecio;
    private javax.swing.JComboBox<String> comboRegistros;
    private javax.swing.JLabel etqCantidad;
    private javax.swing.JLabel etqDetalle;
    private javax.swing.JLabel etqPrecio;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
