/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cap_presentacion;

import cap_datos.ListaRegistros;
import cap_logica.Registro;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Shrike
 */
public class IngresoPresupuesto extends javax.swing.JPanel {
    
    public static int añoInicio;
    public static float crecimientoAnual;
    public static int cantidadAños;

    private static DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    /**
     * Creates new form IngresoPresupuesto
     */
    public IngresoPresupuesto() {
        initComponents();
        
        modeloCombo.removeAllElements();
        modeloCombo.addElement("- Seleccionar -");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        etqAño = new javax.swing.JLabel();
        cajaAño = new javax.swing.JTextField();
        crecimientoAño = new javax.swing.JLabel();
        cajaCrecimiento = new javax.swing.JTextField();
        etqNumAño = new javax.swing.JLabel();
        cajaNumAños = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        etqDetalle = new javax.swing.JLabel();
        cajaDetalle = new javax.swing.JTextField();
        etqCantidad = new javax.swing.JLabel();
        cajaCantidad = new javax.swing.JTextField();
        etqPrecio = new javax.swing.JLabel();
        cajaPrecio = new javax.swing.JTextField();
        costoProduccion = new javax.swing.JLabel();
        cajaCosto = new javax.swing.JTextField();
        botonRegistrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        comboRegistros = new javax.swing.JComboBox<>();
        botonEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridBagLayout());

        etqAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqAño.setText("> Año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(etqAño, gridBagConstraints);

        cajaAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaAño.setForeground(new java.awt.Color(153, 153, 153));
        cajaAño.setText("Ejm: 2019");
        cajaAño.setCaretPosition(0);
        cajaAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaAñoMousePressed(evt);
            }
        });
        cajaAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaAñoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaAñoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaAño, gridBagConstraints);

        crecimientoAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        crecimientoAño.setText("> Crecimiento por año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(crecimientoAño, gridBagConstraints);

        cajaCrecimiento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaCrecimiento.setForeground(new java.awt.Color(153, 153, 153));
        cajaCrecimiento.setText("Ejm: 10");
        cajaCrecimiento.setCaretPosition(0);
        cajaCrecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaCrecimientoMousePressed(evt);
            }
        });
        cajaCrecimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaCrecimientoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaCrecimientoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaCrecimiento, gridBagConstraints);

        etqNumAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqNumAño.setText("> Numero de años:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(etqNumAño, gridBagConstraints);

        cajaNumAños.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaNumAños.setForeground(new java.awt.Color(153, 153, 153));
        cajaNumAños.setText("Ejm: 5");
        cajaNumAños.setCaretPosition(0);
        cajaNumAños.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaNumAñosMousePressed(evt);
            }
        });
        cajaNumAños.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaNumAñosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaNumAñosKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaNumAños, gridBagConstraints);

        botonAceptar.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(60, 0, 0, 0);
        add(botonAceptar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 80, 0, 80);
        add(jSeparator2, gridBagConstraints);

        etqDetalle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqDetalle.setText("> Detalle:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(etqDetalle, gridBagConstraints);

        cajaDetalle.setEditable(false);
        cajaDetalle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaDetalle.setForeground(new java.awt.Color(153, 153, 153));
        cajaDetalle.setText("Ejm: KingKong");
        cajaDetalle.setCaretPosition(0);
        cajaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaDetalleMousePressed(evt);
            }
        });
        cajaDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaDetalleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaDetalleKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaDetalle, gridBagConstraints);

        etqCantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqCantidad.setText("> Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(etqCantidad, gridBagConstraints);

        cajaCantidad.setEditable(false);
        cajaCantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaCantidad.setForeground(new java.awt.Color(153, 153, 153));
        cajaCantidad.setText("Ejm: 2500");
        cajaCantidad.setCaretPosition(0);
        cajaCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaCantidadMousePressed(evt);
            }
        });
        cajaCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaCantidadKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaCantidad, gridBagConstraints);

        etqPrecio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqPrecio.setText("> Precio de venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(etqPrecio, gridBagConstraints);

        cajaPrecio.setEditable(false);
        cajaPrecio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaPrecio.setForeground(new java.awt.Color(153, 153, 153));
        cajaPrecio.setText("Ejm: 15.00");
        cajaPrecio.setCaretPosition(0);
        cajaPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaPrecioMousePressed(evt);
            }
        });
        cajaPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaPrecioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaPrecioKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaPrecio, gridBagConstraints);

        costoProduccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        costoProduccion.setText("> Costo de producción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(costoProduccion, gridBagConstraints);

        cajaCosto.setEditable(false);
        cajaCosto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaCosto.setForeground(new java.awt.Color(153, 153, 153));
        cajaCosto.setText("Ejm: 11.50");
        cajaCosto.setCaretPosition(0);
        cajaCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaCostoMousePressed(evt);
            }
        });
        cajaCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaCostoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaCostoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 50);
        add(cajaCosto, gridBagConstraints);

        botonRegistrar.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        botonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap_imagenes/entradaDatos x48.png"))); // NOI18N
        botonRegistrar.setText("Registrar");
        botonRegistrar.setEnabled(false);
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(botonRegistrar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 80, 0, 80);
        add(jSeparator1, gridBagConstraints);

        comboRegistros.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        comboRegistros.setModel(modeloCombo);
        comboRegistros.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboRegistrosPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(36, 70, 0, 0);
        add(comboRegistros, gridBagConstraints);

        botonEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap_imagenes/basurero x32.png"))); // NOI18N
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 80, 0, 0);
        add(botonEliminar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cajaCantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaCantidadMousePressed

        if(cajaCantidad.getText().equals("Ejm: 2500")){

            cajaCantidad.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaCantidadMousePressed

    private void cajaCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCantidadKeyPressed

        if(cajaCantidad.getText().equals("Ejm: 2500")){

            cajaCantidad.setForeground(new Color(0,0,0));
            cajaCantidad.setText("");
        }
    }//GEN-LAST:event_cajaCantidadKeyPressed

    private void cajaCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCantidadKeyReleased
        boolean letra = false;

        if(cajaCantidad.getCaretPosition() == 0 && cajaCantidad.getText().equals("")){

            cajaCantidad.setText("Ejm: 2500");
            cajaCantidad.setForeground(new Color(153,153,153));
            cajaCantidad.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaCantidad.getText().length(); i++) {
                char c = cajaCantidad.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaCantidad.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaCantidad.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaCantidadKeyReleased

    private void cajaPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaPrecioMousePressed
        if(cajaPrecio.getText().equals("Ejm: 15.00")){

            cajaPrecio.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaPrecioMousePressed

    private void cajaPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaPrecioKeyPressed
        if(cajaPrecio.getText().equals("Ejm: 15.00")){

            cajaPrecio.setForeground(new Color(0,0,0));
            cajaPrecio.setText("");
        }
    }//GEN-LAST:event_cajaPrecioKeyPressed

    private void cajaPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaPrecioKeyReleased
        boolean letra = false;

        if(cajaPrecio.getCaretPosition() == 0 && cajaPrecio.getText().equals("")){

            cajaPrecio.setText("Ejm: 15.00");
            cajaPrecio.setForeground(new Color(153,153,153));
            cajaPrecio.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaPrecio.getText().length(); i++) {
                char c = cajaPrecio.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0' && c != '.'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaPrecio.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaPrecio.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaPrecioKeyReleased

    private void cajaDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaDetalleMousePressed
        if(cajaDetalle.getText().equals("Ejm: KingKong")){

            cajaDetalle.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaDetalleMousePressed

    private void cajaDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDetalleKeyPressed
        if(cajaDetalle.getText().equals("Ejm: KingKong")){

            cajaDetalle.setForeground(new Color(0,0,0));
            cajaDetalle.setText("");
        }
    }//GEN-LAST:event_cajaDetalleKeyPressed

    private void cajaDetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDetalleKeyReleased

        if(cajaDetalle.getCaretPosition() == 0 && cajaDetalle.getText().equals("")){

            cajaDetalle.setText("Ejm: KingKong");
            cajaDetalle.setForeground(new Color(153,153,153));
            cajaDetalle.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaDetalleKeyReleased

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed

        try{
            Registro r = new Registro();

            r.setDetalle(cajaDetalle.getText());
            r.setCantidad(Integer.parseInt(cajaCantidad.getText()));
            r.setPrecioVenta(Float.parseFloat(cajaPrecio.getText()));
            r.setCostoProduccion(Float.parseFloat(cajaCosto.getText()));
            

            ListaRegistros.agregar(r);
            modeloCombo.addElement(r);

            /*cajaAño.setText("Ejm: 2019");
            cajaAño.setForeground(new Color(153,153,153));
            cajaAño.setCaretPosition(0);
            cajaCrecimiento.setText("Ejm: 10");
            cajaCrecimiento.setForeground(new Color(153,153,153));
            cajaCrecimiento.setCaretPosition(0);
            cajaNumAños.setText("Ejm: 5");
            cajaNumAños.setForeground(new Color(153,153,153));
            cajaNumAños.setCaretPosition(0);*/
            cajaDetalle.setText("Ejm: KingKong");
            cajaDetalle.setForeground(new Color(153,153,153));
            cajaDetalle.setCaretPosition(0);
            cajaCantidad.setText("Ejm: 2500");
            cajaCantidad.setForeground(new Color(153,153,153));
            cajaCantidad.setCaretPosition(0);
            cajaPrecio.setText("Ejm: 15.00");
            cajaPrecio.setForeground(new Color(153,153,153));
            cajaPrecio.setCaretPosition(0);
            cajaCosto.setText("Ejm: 11.50");
            cajaCosto.setForeground(new Color(153,153,153));
            cajaCosto.setCaretPosition(0);
            
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void comboRegistrosPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboRegistrosPopupMenuWillBecomeInvisible
        if(comboRegistros.getSelectedIndex() == 0){
            botonEliminar.setEnabled(false);
        }else{
            botonEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_comboRegistrosPopupMenuWillBecomeInvisible

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        try{
            
            ListaRegistros.eliminar((Registro)comboRegistros.getSelectedItem());
            
            modeloCombo.removeElementAt(comboRegistros.getSelectedIndex());
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        try{
            if(cajaAño.getText().length() == 4){
                añoInicio = Integer.parseInt(cajaAño.getText());  
                crecimientoAnual = Float.parseFloat(cajaCrecimiento.getText());
                cantidadAños = Integer.parseInt(cajaNumAños.getText());
                
                cajaAño.setEditable(false);
                cajaCrecimiento.setEditable(false);
                cajaNumAños.setEditable(false);
                botonAceptar.setEnabled(false);
                
                cajaDetalle.setEditable(true);
                cajaCantidad.setEditable(true);
                cajaPrecio.setEditable(true);
                cajaCosto.setEditable(true);
                botonRegistrar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "Año incorrecto",
                    "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void cajaAñoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaAñoMousePressed
        // TODO add your handling code here:
        if(cajaAño.getText().equals("Ejm: 2019")){

            cajaAño.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaAñoMousePressed

    private void cajaAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaAñoKeyPressed
        // TODO add your handling code here:
        if(cajaAño.getText().equals("Ejm: 2019")){

            cajaAño.setForeground(new Color(0,0,0));
            cajaAño.setText("");
        }
    }//GEN-LAST:event_cajaAñoKeyPressed

    private void cajaAñoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaAñoKeyReleased
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaAño.getCaretPosition() == 0 && cajaAño.getText().equals("")){

            cajaAño.setText("Ejm: 2019");
            cajaAño.setForeground(new Color(153,153,153));
            cajaAño.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaAño.getText().length(); i++) {
                char c = cajaAño.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaAño.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaAño.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaAñoKeyReleased

    private void cajaCrecimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaCrecimientoMousePressed
        // TODO add your handling code here:
        if(cajaCrecimiento.getText().equals("Ejm: 10")){

            cajaCrecimiento.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaCrecimientoMousePressed

    private void cajaCrecimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCrecimientoKeyPressed
        // TODO add your handling code here:
        if(cajaCrecimiento.getText().equals("Ejm: 10")){

            cajaCrecimiento.setForeground(new Color(0,0,0));
            cajaCrecimiento.setText("");
        }
    }//GEN-LAST:event_cajaCrecimientoKeyPressed

    private void cajaCrecimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCrecimientoKeyReleased
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaCrecimiento.getCaretPosition() == 0 && cajaCrecimiento.getText().equals("")){

            cajaCrecimiento.setText("Ejm: 10");
            cajaCrecimiento.setForeground(new Color(153,153,153));
            cajaCrecimiento.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaCrecimiento.getText().length(); i++) {
                char c = cajaCrecimiento.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0' && c != '.'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaCrecimiento.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaCrecimiento.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaCrecimientoKeyReleased

    private void cajaNumAñosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaNumAñosMousePressed
        // TODO add your handling code here:
        if(cajaNumAños.getText().equals("Ejm: 5")){

            cajaNumAños.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaNumAñosMousePressed

    private void cajaNumAñosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNumAñosKeyPressed
        // TODO add your handling code here:
        if(cajaNumAños.getText().equals("Ejm: 5")){

            cajaNumAños.setForeground(new Color(0,0,0));
            cajaNumAños.setText("");
        }
    }//GEN-LAST:event_cajaNumAñosKeyPressed

    private void cajaNumAñosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNumAñosKeyReleased
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaNumAños.getCaretPosition() == 0 && cajaNumAños.getText().equals("")){

            cajaNumAños.setText("Ejm: 5");
            cajaNumAños.setForeground(new Color(153,153,153));
            cajaNumAños.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaNumAños.getText().length(); i++) {
                char c = cajaNumAños.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaNumAños.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaNumAños.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaNumAñosKeyReleased

    private void cajaCostoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaCostoMousePressed
        // TODO add your handling code here:
        if(cajaCosto.getText().equals("Ejm: 11.50")){

            cajaCosto.setCaretPosition(0);
        }
    }//GEN-LAST:event_cajaCostoMousePressed

    private void cajaCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCostoKeyPressed
        // TODO add your handling code here:
        if(cajaCosto.getText().equals("Ejm: 11.50")){

            cajaCosto.setForeground(new Color(0,0,0));
            cajaCosto.setText("");
        }
    }//GEN-LAST:event_cajaCostoKeyPressed

    private void cajaCostoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCostoKeyReleased
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaCosto.getCaretPosition() == 0 && cajaCosto.getText().equals("")){

            cajaCosto.setText("Ejm: 11.50");
            cajaCosto.setForeground(new Color(153,153,153));
            cajaCosto.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaCosto.getText().length(); i++) {
                char c = cajaCosto.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0' && c != '.'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaCosto.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaCosto.setForeground(new Color(0,0,0)); // negro
            }
        }
    }//GEN-LAST:event_cajaCostoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField cajaAño;
    private javax.swing.JTextField cajaCantidad;
    private javax.swing.JTextField cajaCosto;
    private javax.swing.JTextField cajaCrecimiento;
    private javax.swing.JTextField cajaDetalle;
    private javax.swing.JTextField cajaNumAños;
    private javax.swing.JTextField cajaPrecio;
    private javax.swing.JComboBox<String> comboRegistros;
    private javax.swing.JLabel costoProduccion;
    private javax.swing.JLabel crecimientoAño;
    private javax.swing.JLabel etqAño;
    private javax.swing.JLabel etqCantidad;
    private javax.swing.JLabel etqDetalle;
    private javax.swing.JLabel etqNumAño;
    private javax.swing.JLabel etqPrecio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
